services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_USER_DB=user_progress_db
      - POSTGRES_PERF_DB=performance_db
      - POSTGRES_ANALYTICS_DB=usage_analytics_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - virtual-labs-network

  pgadmin:
    image: postgres:latest
    environment:
      - PGPASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["tail", "-f", "/dev/null"] # Keep container running
    stop_grace_period: 5s
    networks:
      - virtual-labs-network

  user-progress:
    build: ./user-progress-service
    ports:
      - "8004:8000"
    volumes:
      - ./user-progress-service/app:/app/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/user_progress_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - virtual-labs-network

  performance-reporting:
    build: ./performance-reporting-service
    ports:
      - "8005:8000"
    volumes:
      - ./performance-reporting-service/app:/app/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/performance_db
      - USER_PROGRESS_SERVICE_URL=http://user-progress:8000
    depends_on:
      db:
        condition: service_healthy
      user-progress:
        condition: service_started
    networks:
      - virtual-labs-network

  usage-analytics:
    build: ./usage-analytics-service
    ports:
      - "8006:8000"
    volumes:
      - ./usage-analytics-service/app:/app/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/usage_analytics_db
      - USER_PROGRESS_SERVICE_URL=http://user-progress:8000
    depends_on:
      db:
        condition: service_healthy
      user-progress:
        condition: service_started
    networks:
      - virtual-labs-network
  
  integration-service:
    build: ./integration
    ports:
      - "8007:8007"
    volumes:
      - ./integration:/app
    environment:
      - INTEGRATION_API_PORT=8007
      - LAB_MONITORING_URL=http://host.docker.internal:3003
      - RESOURCE_ALLOCATION_URL=http://host.docker.internal:3005
      - PERFORMANCE_SERVICE_URL=http://host.docker.internal:3004
      - USAGE_ANALYTICS_URL=http://usage-analytics:8000
      - PERFORMANCE_REPORTING_URL=http://performance-reporting:8000
    depends_on:
      - usage-analytics
      - performance-reporting
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - virtual-labs-network

volumes:
  postgres_data:

networks:
  virtual-labs-network:
    name: virtual-labs-network
    driver: bridge