services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_progress_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - virtual-labs-network

  user-progress:
    build: .
    ports:
      - "8004:8000"
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/user_progress_db
    depends_on:
      - db
    networks:
      - virtual-labs-network

volumes:
  pgdata:

networks:
  virtual-labs-network:
    external: true
