version: '3.8'

services:
  user-progress:
    build: .
    ports:
      - "8004:8000"
    volumes:
      - ./app:/app/app
    networks:
      - virtual-labs-network

networks:
  virtual-labs-network:
    external: true